### ISSUE TITLE
Integrate Dependabot 

### ISSUE THREAD

**Issue by Zerotask** [FrankFlamme/TwitchBot#15]
> Dependabot creates pull requests to keep your dependencies up-to-date. 

Docs: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

Since a few weeks dependabot is a part of GitHub and it can be accessed via Insights -> Dependency Graph

![grafik](https://user-images.githubusercontent.com/20150243/86289920-cc26eb00-bbec-11ea-9a23-2d4bac50bd2b.png)

**Comment by FrankFlamme** [comment]
Dependabot is implemented in the repository.
Thanks for the request. 👍

**Comment by Zerotask** [comment]
To fulfill conventional commits you can also define a commit prefix in your dependabot.yml

```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps): "
```
See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#commit-message
